---
- name: testing the block 
  hosts: compute
  tasks:
  - name: testing block 
    block:
    - name: lineinfile
      lineinfile:     
         path: /tmp/test.log
         line: test
    rescue:
    - debug:
       msg:  "file is not exist" 
